### ISSUE TITLE
Doesn't download images

### ISSUE THREAD

**Issue by protist** [samanbarghi/ngphotodownloader#1]
I think the webpage has probably changed since this script was written. It currently doesn't work, since there is no `download_link` in the scraped page. If you replace the curl line with the following, it works.

```
img="http:$(curl http://photography.nationalgeographic.com/photography/photo-of-the-day/ | awk 'found && /<\/div>/ {exit}; found ;/class="primary_photo"/ {found=1}' | grep -oP '(?<=img src=")[^"]*(?=")')"
```

**Comment by samanbarghi** [comment]
@protist Thanks, I have not updated this for a while. Updated the code. You might also want to check http://peterlevi.com/variety/, although I find it a bit heavy to run in the background and caused all kinds of issues the last time I used it.

**Comment by protist** [comment]
Thank you. Yes, I used variety at one stage, but it was a bit buggy for me too.
