### ISSUE TITLE
Download link changed again

### ISSUE THREAD

**Issue by protist** [samanbarghi/ngphotodownloader#2]
Hi, the download link has changed again. You can now get with the following code. (Apologies for the horrible `'` escaping.

```
img="$(curl http://www.nationalgeographic.com/photography/photo-of-the-day/ -s | grep -oP '(?<='\''aemLeadImage'\'': '\'')[^'\'']*')"
```

N.B. the image file's url is now unnamed, so you'll have to specifically save it to a filename, rather than just bare `wget`.

**Comment by protist** [comment]
I've modified your code a bit, otherwise I'd submit a pull request. If it's useful, I've just decided to save to the alphanumeric string, for the purposes of seeing if the picture has already been downloaded.

```
-   img_file=`basename $img`
+   img_file=`basename $img`.jpg
    if [ -f "$img_file" ]
    then
        echo "File already exists"
    else
-       wget "$img"
+       curl "$img" > $img_file
```

**Comment by samanbarghi** [comment]
@protist I forgot to update the code. Thanks for informing me about the link being changed as I reinstalled linux on my laptop and did not have the script running. I also applied your suggestion with a twist, I am using md5sum to shorten the file name, as the filenames from ng are pretty long.
