### ISSUE TITLE
"No Wallpaper today"

### ISSUE THREAD

**Issue by steynwestbeek** [samanbarghi/ngphotodownloader#3]
As of yesterday (or maybe the day before) it reports "No Wallpaper today". Not sure where the origin of the problem lies.

**Comment by samanbarghi** [comment]
@steynwestbeek thanks for  letting me know, I was to busy to notice the photo was the same for few days. They updated the HTML source code and the script stopped working. I just updated the code and it should work fine for now. Just pull and should be good to go. 

Thanks

**Comment by steynwestbeek** [comment]
Awesome, thanks for the quick fix!
